In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
data = pd.read_csv("Social_Network_Ads.csv")
data.head()


User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [16]:
data.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [38]:
x = data[["Age","EstimatedSalary"]].values
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [40]:
y=data["Purchased"].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [42]:
from sklearn.model_selection import train_test_split

In [44]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=45)

In [46]:
x_train.shape

(300, 2)

In [48]:
x_train = x_train.astype(float)

In [50]:
x_test = x_test.astype(float)

In [52]:
x_test.dtype

dtype('float64')

In [54]:
from sklearn.preprocessing import StandardScaler

In [56]:
sc = StandardScaler()

In [58]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [60]:
x_train

array([[ 0.42118245,  0.15177847],
       [-1.86353366, -1.48066604],
       [ 0.81852438, -1.10170571],
       [-0.17483045, -0.46038822],
       [-0.27416593,  0.61819119],
       [ 1.71254373,  1.75507219],
       [-0.67150786,  0.12262768],
       [ 0.22251148, -0.28548345],
       [ 1.01719535, -0.83934855],
       [-0.07549497,  0.23923086],
       [ 0.42118245, -0.46038822],
       [ 0.32184696, -0.51868981],
       [-0.07549497,  0.12262768],
       [-0.67150786, -1.04340412],
       [-1.16818528,  0.41413563],
       [ 1.11653083, -0.98510253],
       [ 1.11653083, -0.13972948],
       [ 1.21586631, -1.45151524],
       [ 2.10988566,  0.18092927],
       [-0.77084335,  0.29753245],
       [-1.16818528,  0.47243721],
       [-0.96951431, -0.31463425],
       [-0.17483045, -0.19803107],
       [-0.87017883, -0.78104696],
       [-0.57217238, -1.50981683],
       [-0.37350142, -0.78104696],
       [ 0.91785986, -0.5769914 ],
       [-0.07549497,  0.06432609],
       [-1.16818528,

In [62]:
x_test

array([[ 1.41453728,  0.58904039],
       [ 1.51387276,  0.06432609],
       [ 0.22251148,  0.06432609],
       [ 1.91121469, -1.07255491],
       [ 0.22251148, -0.25633266],
       [-1.86353366, -1.42236445],
       [-0.57217238,  0.47243721],
       [-0.27416593,  0.06432609],
       [-1.26752076,  0.50158801],
       [ 2.10988566, -1.18915809],
       [-0.87017883,  0.15177847],
       [ 0.7191889 ,  0.26838165],
       [-1.36685625, -1.10170571],
       [ 1.81187921, -0.28548345],
       [ 0.123176  , -0.81019776],
       [-1.86353366,  0.18092927],
       [-1.16818528,  0.06432609],
       [ 0.91785986, -1.45151524],
       [-1.96286914, -0.51868981],
       [-1.76419818, -1.36406286],
       [-0.07549497,  0.26838165],
       [ 1.71254373,  1.60931821],
       [-0.27416593, -0.43123742],
       [ 0.22251148,  0.15177847],
       [-0.87017883, -0.25633266],
       [-1.96286914, -0.05227709],
       [-0.87017883,  2.27978649],
       [-1.26752076,  0.58904039],
       [ 0.91785986,

In [64]:
from sklearn.neighbors import KNeighborsClassifier

In [65]:
classifier = KNeighborsClassifier(n_neighbors=3)

In [68]:
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [70]:
y_pred=classifier.predict(x_test)

In [72]:
y_pred

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0], dtype=int64)

In [74]:
from sklearn.metrics import confusion_matrix

In [76]:
cn = confusion_matrix(y_test,y_pred)
cn

array([[57,  5],
       [ 4, 34]], dtype=int64)

In [78]:
from sklearn.metrics import accuracy_score

In [80]:
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.91

In [95]:
from sklearn.metrics import accuracy_score
l=[1,3,5,9,11,13,15,17]
for i in l:
    classifier=KNeighborsClassifier(n_neighbors=i)
    classifier.fit(x_train,y_train)
    y_pred=classifier.predict(x_test)
    accuracy=accuracy_score(y_test,y_pred)
    print(accuracy,"==",i)

0.81 == 1
0.91 == 3
0.89 == 5
0.92 == 9
0.91 == 11
0.91 == 13
0.9 == 15
0.9 == 17
